### ISSUE TITLE
Strided Interval: Least upper bound is incorrect (depending on the order of arguments)

### ISSUE THREAD

**Issue by michael-schwarz** [peterrum/po-lab-2018#51]
This only occurs if 0[0,0] is the receiver (i.e. 0[0,0].leastUpperBound(sth) but
sth.leastUpperBound(0[0,0]) works)

```
3[0, 3]_32 lub 0[0, 0]_32 = 1[0, 3]_32
5[0, 5]_32 lub 0[0, 0]_32 = 1[0, 5]_32
6[0, 6]_32 lub 0[0, 0]_32 = 2[0, 6]_32
7[0, 7]_32 lub 0[0, 0]_32 = 1[0, 7]_32
9[0, 9]_32 lub 0[0, 0]_32 = 1[0, 9]_32
10[0, 10]_32 lub 0[0, 0]_32 = 2[0, 10]_32
11[0, 11]_32 lub 0[0, 0]_32 = 1[0, 11]_32
12[0, 12]_32 lub 0[0, 0]_32 = 4[0, 12]_32
13[0, 13]_32 lub 0[0, 0]_32 = 1[0, 13]_32
14[0, 14]_32 lub 0[0, 0]_32 = 2[0, 14]_32
15[0, 15]_32 lub 0[0, 0]_32 = 1[0, 15]_32
17[0, 17]_32 lub 0[0, 0]_32 = 1[0, 17]_32
18[0, 18]_32 lub 0[0, 0]_32 = 2[0, 18]_32
19[0, 19]_32 lub 0[0, 0]_32 = 1[0, 19]_32
20[0, 20]_32 lub 0[0, 0]_32 = 4[0, 20]_32
21[0, 21]_32 lub 0[0, 0]_32 = 1[0, 21]_32
22[0, 22]_32 lub 0[0, 0]_32 = 2[0, 22]_32
23[0, 23]_32 lub 0[0, 0]_32 = 1[0, 23]_32
24[0, 24]_32 lub 0[0, 0]_32 = 8[0, 24]_32
25[0, 25]_32 lub 0[0, 0]_32 = 1[0, 25]_32
26[0, 26]_32 lub 0[0, 0]_32 = 2[0, 26]_32
27[0, 27]_32 lub 0[0, 0]_32 = 1[0, 27]_32
28[0, 28]_32 lub 0[0, 0]_32 = 4[0, 28]_32
29[0, 29]_32 lub 0[0, 0]_32 = 1[0, 29]_32
30[0, 30]_32 lub 0[0, 0]_32 = 2[0, 30]_32
31[0, 31]_32 lub 0[0, 0]_32 = 1[0, 31]_32
33[0, 33]_32 lub 0[0, 0]_32 = 1[0, 33]_32
34[0, 34]_32 lub 0[0, 0]_32 = 2[0, 34]_32
35[0, 35]_32 lub 0[0, 0]_32 = 1[0, 35]_32
36[0, 36]_32 lub 0[0, 0]_32 = 4[0, 36]_32
37[0, 37]_32 lub 0[0, 0]_32 = 1[0, 37]_32
38[0, 38]_32 lub 0[0, 0]_32 = 2[0, 38]_32
39[0, 39]_32 lub 0[0, 0]_32 = 1[0, 39]_32
40[0, 40]_32 lub 0[0, 0]_32 = 8[0, 40]_32
41[0, 41]_32 lub 0[0, 0]_32 = 1[0, 41]_32
42[0, 42]_32 lub 0[0, 0]_32 = 2[0, 42]_32
43[0, 43]_32 lub 0[0, 0]_32 = 1[0, 43]_32
44[0, 44]_32 lub 0[0, 0]_32 = 4[0, 44]_32
45[0, 45]_32 lub 0[0, 0]_32 = 1[0, 45]_32
46[0, 46]_32 lub 0[0, 0]_32 = 2[0, 46]_32
47[0, 47]_32 lub 0[0, 0]_32 = 1[0, 47]_32
48[0, 48]_32 lub 0[0, 0]_32 = 16[0, 48]_32
```

**Comment by jagottf** [comment]
Not related to #24.

**Comment by michael-schwarz** [comment]
Looks like it is caused by a copy-constructor not copying isBot, I'll track it down so you can focus on the other stuff @jagottf .

**Comment by jagottf** [comment]
I implemented lub from scratch.
The c++ implementation is not tested in detail, yet, but the algorithm is very unlikely to by wrong now.

**Comment by michael-schwarz** [comment]
fixed as far as i can see. I'll write more tests and reopen if appropriate

**Comment by michael-schwarz** [comment]
Unfortunately, @jagottf the fix only moved the problem. Now we see negative strides and the LUB operation is no longer symetric :disappointed: 

`0[1, 1]_32 -> lub( 0[0, 0]_32 ) =  1[0, 1]_32` :+1: 

but also
` 0[0, 0]_32 -> lub( 0[1, 1]_32) = -1[1, 0]_32` :-1: 

Maybe you can give us a rundown of what the algorithm is supposed to do? You're the one who went the deepest into the strided intervals, but maybe we can help find the bug :smile:

**Comment by jagottf** [comment]
Again: There are no negative strides, it‘s an error in the printing function. The actual stride is 2^32-1.
Therefore both results actually represent the same set, the second one just isn‘t normalized.
Nevertheless it’s a bug, as other functions rely on there arguments being normalized.
Feel free to fix it, if you need a quick fix, but probably the code can be further streamlined, as `normalize` can do some of the work by itself.

**Comment by jagottf** [comment]
Should be fixed by 931606bc028740e209f50a78ac1cbd949b717f64.
There was also still an overflow bug in `size`.

**Comment by michael-schwarz** [comment]
All right, thanks, I forgot that!
I'll push a solution that calls normalize at the end as a simple fix pending a proper solution
However, it is still broken (for stride == 1) :sob: 

```
new 0[2, 2]_32    prev 1[0, 1]_32
prev->lub(new)                 1[0, 2]_32
prev->lub(new) (norm.)         1[0, 2]_32
new->lub(prev)                 1[2, 1]_32
new->lub(prev) (norm.)         1[0, 4294967295]_32

```
The bug is definitely here as 1[2,1] is indeed correctly normalized to top.

**Comment by michael-schwarz** [comment]
@jagottf: you were a bit quicker, let me check if the issue is solved with the new one

**Comment by michael-schwarz** [comment]
Indeed fixed by 931606b.

**Comment by michael-schwarz** [comment]
And here we go again:

With big/negative numbers: we still get non-normalized intervals and subsequently it breaks. This is the example of an interval representing [-2,0]. I'll push the code in a second.
Maybe it would be good to take a look at your algorithm together @jagottf ?

```
new 0[0, 0]_32    prev []_32
prev->lub(new)                 0[0, 0]_32
prev->lub(new) (norm.)         0[0, 0]_32
new->lub(prev)                 0[0, 0]_32
new->lub(prev) (norm.)         0[0, 0]_32
new 0[4294967295, 4294967295]_32    prev 0[0, 0]_32
prev->lub(new)                 -1[0, 4294967295]_32
prev->lub(new) (norm.)         -1[0, 4294967295]_32
new->lub(prev)                 -1[0, 4294967295]_32
new->lub(prev) (norm.)         -1[0, 4294967295]_32
new 0[4294967294, 4294967294]_32    prev -1[0, 4294967295]_32
prev->lub(new)                 T_32
prev->lub(new) (norm.)         T_32
new->lub(prev)                 T_32
new->lub(prev) (norm.)         T_32
```

**Comment by jagottf** [comment]
I try to add some comments every time I touch the code and started writing an explanation for the algorithms, but this currently takes longer than just fixing it myself.
I only tested for soundness, so an unnecessarily imprecise result wasn't detected by my tests.
The imprecision was due to that fact that shifting an interval (add/subtract some amount from `begin` and `end`) may result in an unnormalized interval.
Fixed by e97d9c9475d2839bf654ff93b92edd30ed3efedd?

**Comment by jagottf** [comment]
lub 2[0, 2]_32 0[1, 1]_32 probably still behaves bad.

**Comment by michael-schwarz** [comment]
I won't be able to do any testing until tomorrow morning. To test it you
can just execute the run.sh in the tests folder on master

**Comment by jagottf** [comment]
Indeed `([1, 1]_32).leastUpperBound(2[0, 2]_32)` = `T`.
The root of the problem is that MSIs do not form a lattice (_the least_ upper bound wrt. the subset relation does not exist in general). The best we can achieve, is _a minimal_ upper bound were one element is smaller than the other if it contains fewer elements (not necessarily a subset).
Finding such a minimal upper bound should be possible efficiently (in quadratic time wrt. the bit width), but may be considerably more complex than the current implementation.

**Comment by michael-schwarz** [comment]
@jagottf , @arosch and I are gonna do a new implementation of this from scratch later on
